# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern *.yaml,
  # and age is used
  # - path_regex: .yaml$

  ## This key is the public key of the age key pair
  - kms: "arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012"
