# https://docs.digger.dev/self-host/deploy-docker-compose#create-github-app
# docker-compose.yml
version: '3.7'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    image: "registry.digger.dev/diggerhq/digger_backend:latest"
    env_file:
      - .env
    ports:
      - "3000:3000"

